version: "3"

services:
    influxdb:
        restart: unless-stopped
        container_name: influxdb
        image: influxdb:1.7.8-alpine
        volumes:
            - ./influxdb/etc:/etc/influxdb
            - influxdb-lib:/var/lib/influxdb
        env_file:
            - ./demo.env
        ports:
            - 8083:8083
            - 8086:8086
        privileged: true

    grafana:
        restart: unless-stopped
        container_name: grafana
        image: grafana/grafana:6.4.2
        volumes:
            - ./grafana/etc:/etc/grafana:ro
            - grafana-lib:/var/lib/grafana
            - grafana-log:/var/log/grafana
        links:
            - influxdb:influxdb
        env_file:
            - ./demo.env
        ports:
            - 3000:3000
        depends_on:
            - influxdb
        privileged: true

volumes:
  influxdb-lib:
    external: false

  grafana-lib:
    external: false

  grafana-log:
    external: false
